packageExtensions:
  # TEMP: https://github.com/shadowwalker/next-pwa/issues/222
  'next-pwa@5.6.0':
    dependencies:
      '@babel/core': '^7.0.0'
      webpack: '>=5.1.0 <6.0.0'
  # TEMP: https://github.com/webpro/knip/issues/327
  '@pnpm/workspace.pkgs-graph@2.0.15':
    peerDependencies:
      '@pnpm/logger': '^5.0.0'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
