compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@pnpm/workspace.pkgs-graph@2.0.15':
    peerDependencies:
      '@pnpm/logger': ^5.0.0
  next-pwa@5.6.0:
    dependencies:
      '@babel/core': ^7.0.0
      webpack: '>=5.1.0 <6.0.0'

yarnPath: .yarn/releases/yarn-4.4.0.cjs
