# TEMP: Avoid errors in ESLint and Prettier VSCode extensions.
#   See https://is.gd/ne40Ud, https://is.gd/nkQqxC
nodeLinker: node-modules

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  next-pwa@5.6.0:
    dependencies:
      '@babel/core': ^7.0.0
      webpack: '>=5.9.0 <6.0.0'
  '@typescript-eslint/utils@5.62.0':
    peerDependencies:
      typescript: '>= 3.7.0-beta'
  eslint-plugin-storybook@0.8.0:
    peerDependencies:
      typescript: '>= 3.7.0-beta'

yarnPath: .yarn/releases/yarn-4.4.0.cjs
