services:
  frontend:
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME:?}
        - USER_NAME=${FRONTEND_USER_NAME:?}
    volumes:
      - .:/home/${FRONTEND_USER_NAME:?}/${COMPOSE_PROJECT_NAME:?}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${FRONTEND_PORT:-3000}:3000
      - ${STORYBOOK_PORT:-6006}:6006
    command: bash -c "node node_modules/.bin/next dev"
